image: ubuntu:20.04
# before_script:
#   - apt update && apt install -y curl

stages:        # List of stages for jobs, and their order of execution
  - update-inmage2compose

update:       # This job runs in the build stage, which runs first.
  stage: update-inmage2compose
  script:
    - uname -a