language_timezone_mapping = {
    "zh-Hans": "Asia/Shanghai",
    "en-US": "Asia/Shanghai",
    "zh-Hant": "Asia/Shanghai",
    "pt-BR": "Asia/Shanghai",
    "es-ES": "Asia/Shanghai",
    "fr-FR": "Asia/Shanghai",
    "de-DE": "Asia/Shanghai",
    "ja-JP": "Asia/Shanghai",
    "ko-KR": "Asia/Shanghai",
    "ru-RU": "Asia/Shanghai",
    "it-IT": "Asia/Shanghai",
    "uk-UA": "Asia/Shanghai",
    "vi-VN": "Asia/Shanghai",
    "ro-RO": "Asia/Shanghai",
    "pl-PL": "Asia/Shanghai",
    "hi-IN": "Asia/Shanghai",
    "tr-TR": "Asia/Shanghai",
}
